## This sample values-override file shows how to override few parameters based on the Use Case with Horizontal Scaling (HS).
## Please provide the necessary values against each attribute by replacing "<>" depending upon the use case (CE deployment package, etc). For more details, please refer README.
## 
namespace: netskope
mongodb:
  auth:
    rootPassword: <>
    cteAdminPassword: <>
rabbitmq:
  auth:
    rabbitmqDefaultPassword: <>
core:
  image: <>
  workerConcurrency: <>
  replicaCount:
    worker: <>
  rabbitmqAvailableStorage: "<>"
  auth:
    analyticsToken: <>
    jwtToken: <>
ui:
  image: <>
