apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app.kubernetes.io/name: netskope-ce-rabbitmq-config
  name: netskope-ce-rabbitmq-config
  namespace: <NAMESPACE_NAME>
data:
  custom.conf: |
    consumer_timeout = 864000000
    disk_free_limit.absolute = 2GB
