{{ $cte_cert := .Files.Get "certificates/cte_cert.crt" }}
{{ $cte_cert_key := .Files.Glob "certificates/cte_cert_key.key" }}
{{- if and .Values.ui.secrets.create .Values.ui.ssl }}
{{- if and $cte_cert $cte_cert_key  }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.ui.secrets.name }}
  labels:
    app.kubernetes.io/name: {{ .Values.ui.secrets.name }}
    {{- include "resource.labels.commonLabels" . | nindent 4 }}
    {{- if .Values.commonLabels }}
    {{- include "tplvalues.render" ( dict "value" .Values.commonLabels "context" $ ) | nindent 4 }}
    {{- end }}
  namespace: {{ include "namespace.name" . }}
  {{- if .Values.commonAnnotations }}
  annotations: 
    {{- include "tplvalues.render" ( dict "value" .Values.commonAnnotations "context" $ ) | nindent 4 }}
  {{- end }}
type: Opaque
data:
{{ (.Files.Glob "certificates/*").AsSecrets | indent 2 }} 
{{- else }}
{{- fail "If SSL enabled then SSL certs file and cert private key file must be present at certificates dir with cte_cert.crt cte_cert_key.key filenames." }}
{{- end }}
{{- end }}
