{{- if .Values.ui.rbac.create }}
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ printf "%s-ui-rolebinding" .Chart.Name }}
  labels:
    app.kubernetes.io/name: {{ printf "%s-ui-rolebinding" .Chart.Name }}
    {{- include "resource.labels.commonLabels" . | nindent 4 }}
    {{- if .Values.commonLabels }}
    {{- include "tplvalues.render" ( dict "value" .Values.commonLabels "context" $ ) | nindent 4 }}
    {{- end }}
  namespace: {{ include "namespace.name" . }}
roleRef:
  kind: Role
  name: {{ printf "%s-ui-role" .Chart.Name }}
  apiGroup: rbac.authorization.k8s.io
subjects:
  - kind: ServiceAccount
    name: {{ include "serviceAccountName.name" .}}
    namespace: {{ include "namespace.name" . }}
{{- end }}
