apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: netskope-ce-ui
  name: netskope-ce-ui
  namespace: <NAMESPACE_NAME>
spec:
  ports:
    - name: "80"
      port: 80
      targetPort: 3000
  selector:
    app.kubernetes.io/name: ui
  type: ClusterIP
