apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    app.kubernetes.io/name: mongodb
  name: netskope-ce-mongodb
  namespace: <NAMESPACE_NAME>
spec:
  replicas: 3
  selector:
    matchLabels:
      app.kubernetes.io/name: mongodb
  serviceName: netskope-ce-mongodb-headless
  template:
    metadata:
      labels:
        app.kubernetes.io/name: mongodb
      namespace: <NAMESPACE_NAME>
    spec:
      initContainers:
        - name: volume-permissions
          image: busybox:latest
          command:
            - sh
          args:
            - -ec
            - |
              mkdir -p /bitnami/mongodb
              chown -R 1001:1001 /bitnami/mongodb
          securityContext:
            privileged: true
          volumeMounts:
            - name: netskope-ce-mongodb-datadir
              mountPath: /bitnami/mongodb
      containers:
        - command:
            - /scripts/setup.sh
          env:
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: metadata.name
            - name: NAMESPACE_NAME
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: metadata.namespace
            - name: STATEFULSET_NAME
              value: netskope-ce-mongodb
            - name: K8S_SERVICE_NAME
              value: netskope-ce-mongodb-headless
            - name: MONGODB_INITIAL_PRIMARY_HOST
              value: $(STATEFULSET_NAME)-0.$(K8S_SERVICE_NAME).$(NAMESPACE_NAME).svc.cluster.local
            - name: MONGODB_REPLICA_SET_NAME
              value: rs1
            - name: MONGODB_EXTRA_DATABASES
              value: cte
            - name: MONGODB_ADVERTISED_HOSTNAME
              value: $(POD_NAME).$(K8S_SERVICE_NAME).$(NAMESPACE_NAME).svc.cluster.local
            - name: MONGODB_ROOT_USER
              valueFrom:
                secretKeyRef:
                  key: mongodb-root-username
                  name: netskope-ce-mongodb
            - name: MONGODB_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: mongodb-root-password
                  name: netskope-ce-mongodb
            - name: MONGODB_REPLICA_SET_KEY
              valueFrom:
                secretKeyRef:
                  key: mongodb-replica-set-key
                  name: netskope-ce-mongodb
          image: <MONGODB_IMAGE_NAME>
          imagePullPolicy: IfNotPresent
          name: netskope-ce-mongodb
          ports:
            - containerPort: 27017
              name: mongodb
              protocol: TCP
          livenessProbe:
            exec:
              command:
                - /bitnami/scripts/ping-mongodb.sh
            failureThreshold: 6
            initialDelaySeconds: 30
            periodSeconds: 60
            successThreshold: 1
            timeoutSeconds: 60
          readinessProbe:
            exec:
              command:
                - /bitnami/scripts/readiness-probe.sh
            failureThreshold: 6
            initialDelaySeconds: 30
            periodSeconds: 60
            successThreshold: 1
            timeoutSeconds: 30
          resources:
            limits:
              memory: 2Gi
              cpu: 1000m
            requests:
              memory: 1Gi
              cpu: 500m
          securityContext:
            runAsNonRoot: true
            privileged: true
          volumeMounts:
            - mountPath: /bitnami/mongodb
              name: netskope-ce-mongodb-datadir
            - mountPath: /bitnami/scripts
              name: netskope-ce-mongodb-common-scripts-vol
            - mountPath: /scripts/setup.sh
              name: netskope-ce-mongodb-scripts-vol
              subPath: setup.sh
      restartPolicy: Always
      serviceAccount: <SERVICEACCOUNT_NAME>
      volumes:
        - configMap:
            defaultMode: 360
            name: netskope-ce-mongodb-common-scripts
          name: netskope-ce-mongodb-common-scripts-vol
        - configMap:
            defaultMode: 493
            name: netskope-ce-mongodb-scripts
          name: netskope-ce-mongodb-scripts-vol
  updateStrategy:
    type: RollingUpdate
  volumeClaimTemplates:
    - metadata:
        name: netskope-ce-mongodb-datadir
      spec:
        accessModes:
          - ReadWriteOnce
        storageClassName: <STORAGE_CLASS>
        resources:
          requests:
            storage: 1Gi
