apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: netskope-ce-mongodb
  name: netskope-ce-mongodb
  namespace: <NAMESPACE_NAME>
spec:
  ports:
    - name: mongodb
      port: 27017
      protocol: TCP
      targetPort: mongodb
  publishNotReadyAddresses: true
  selector:
    app.kubernetes.io/name: mongodb
  sessionAffinity: None
  type: ClusterIP
